### ISSUE TITLE
Note of gratitude

### ISSUE THREAD

**Issue by pm64** [Andersen27/Photino.Blazor.Docking#1]
Apologies for misusing the issues section here -- but just wanted to thank you for sharing this incredible work. I am new to Photino and was very pleased to find this. It is stunning. Massive thanks!!

**Comment by Andersen27** [comment]
Thanks, i’m very pleased to get such a feedback!

**Comment by wdichler** [comment]
The same from my side, it's incredible. It is the missing piece for photino. 👍👍👍
